name: Release Update

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Workflows
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Commit
        uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Build Plugin
        run: |
          ./gradlew build

      - name: Create Release
        if: ${{ github.repository == 'mindustry-antigrief/PacketPlugin' && (github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch') }}
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          body: |
            Packet Plugin ${{ github.run_number }} (${{ env.COMMIT }})
            See README.md for installation instructions
            **Commit Message:**
            *${{ github.event.head_commit.message }}*

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/libs/PacketPlugin.jar
          asset_name: PacketPlugin.jar
          asset_content_type: application/zip

      - name: Upload Artifact # Only uploaded on fail to save time
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: Zipped Jar
          path: build/libs/PacketPlugin.jar
